# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='收件地址')),
                ('name', models.CharField(max_length=20, verbose_name='收件人')),
                ('mobile', models.CharField(max_length=30, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mugshot',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to='user/%Y/%m', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='realname',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', '保密'), ('1', '男'), ('2', '女')], max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_rank',
            field=models.CharField(blank=True, choices=[('0', '普通会员'), ('1', '铜牌会员'), ('2', '银牌会员'), ('3', '金牌会员')], default='0', max_length=1, verbose_name='用户级别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('0', '停用'), ('1', '启用')], default='1', max_length=1, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
