# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_date',), 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='creation_date',
            new_name='created_date',
        ),
    ]
